- name: test playbook
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: ensure docker services are up and running
    service:
      name: docker
      state: started
      enabled: yes

  - name: ensure dir is exists
    file:
      path: /clone
      state: directory

  - name: clone the data from git hub
    git:
      repo: https://github.com/bschethan86/linux.git
      dest: /clone
      version: master
      force: yes

  - name: start the container
    shell:  docker run -itd --rm --name=web1 -p 85:80 httpd
    register: docker_output

  - debug:
      var: docker_output
